---
version: 2

formats:
  - htmlzip

build:
  os : ubuntu-20.04
  tools:
    python: "3.7"
  image: latest

python:
  version: 3.7
  install:
    - requirements: docs/requirements-docs.txt

sphinx:
  configuration: docs/conf.py
