/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "/root/svaidhya/ASN1_file/F1.asn1"
 * 	`asn1c -pdu=all -fno-include-deps -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D /root/svaidhya/28March_ASN1_l2/l2/src/codec_utils/F1AP/`
 */

#ifndef	_Cancel_all_Warning_Messages_Indicator_H_
#define	_Cancel_all_Warning_Messages_Indicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Cancel_all_Warning_Messages_Indicator {
	Cancel_all_Warning_Messages_Indicator_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_Cancel_all_Warning_Messages_Indicator;

/* Cancel-all-Warning-Messages-Indicator */
typedef long	 Cancel_all_Warning_Messages_Indicator_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Cancel_all_Warning_Messages_Indicator_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Cancel_all_Warning_Messages_Indicator;
extern const asn_INTEGER_specifics_t asn_SPC_Cancel_all_Warning_Messages_Indicator_specs_1;
asn_struct_free_f Cancel_all_Warning_Messages_Indicator_free;
asn_struct_print_f Cancel_all_Warning_Messages_Indicator_print;
asn_constr_check_f Cancel_all_Warning_Messages_Indicator_constraint;
xer_type_decoder_f Cancel_all_Warning_Messages_Indicator_decode_xer;
xer_type_encoder_f Cancel_all_Warning_Messages_Indicator_encode_xer;
per_type_decoder_f Cancel_all_Warning_Messages_Indicator_decode_uper;
per_type_encoder_f Cancel_all_Warning_Messages_Indicator_encode_uper;
per_type_decoder_f Cancel_all_Warning_Messages_Indicator_decode_aper;
per_type_encoder_f Cancel_all_Warning_Messages_Indicator_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Cancel_all_Warning_Messages_Indicator_H_ */
#include <asn_internal.h>
