/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1.asn1"
 * 	`asn1c -D ./out -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-example`
 */

#include "DRBs-ToBeSetupMod-Item.h"

#include "ULConfiguration.h"
#include "ProtocolExtensionContainer.h"
static asn_TYPE_member_t asn_MBR_DRBs_ToBeSetupMod_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DRBs_ToBeSetupMod_Item, dRBID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRBID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dRBID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DRBs_ToBeSetupMod_Item, qoSInformation),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_QoSInformation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"qoSInformation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DRBs_ToBeSetupMod_Item, uLUPTNLInformation_ToBeSetup_List),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ULUPTNLInformation_ToBeSetup_List,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uLUPTNLInformation-ToBeSetup-List"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DRBs_ToBeSetupMod_Item, rLCMode),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RLCMode,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rLCMode"
		},
	{ ATF_POINTER, 3, offsetof(struct DRBs_ToBeSetupMod_Item, uLConfiguration),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ULConfiguration,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uLConfiguration"
		},
	{ ATF_POINTER, 2, offsetof(struct DRBs_ToBeSetupMod_Item, duplicationActivation),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DuplicationActivation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"duplicationActivation"
		},
	{ ATF_POINTER, 1, offsetof(struct DRBs_ToBeSetupMod_Item, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_4624P34,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_DRBs_ToBeSetupMod_Item_oms_1[] = { 4, 5, 6 };
static const ber_tlv_tag_t asn_DEF_DRBs_ToBeSetupMod_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DRBs_ToBeSetupMod_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dRBID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* qoSInformation */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* uLUPTNLInformation-ToBeSetup-List */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* rLCMode */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* uLConfiguration */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* duplicationActivation */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_DRBs_ToBeSetupMod_Item_specs_1 = {
	sizeof(struct DRBs_ToBeSetupMod_Item),
	offsetof(struct DRBs_ToBeSetupMod_Item, _asn_ctx),
	asn_MAP_DRBs_ToBeSetupMod_Item_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_DRBs_ToBeSetupMod_Item_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	7,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DRBs_ToBeSetupMod_Item = {
	"DRBs-ToBeSetupMod-Item",
	"DRBs-ToBeSetupMod-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_DRBs_ToBeSetupMod_Item_tags_1,
	sizeof(asn_DEF_DRBs_ToBeSetupMod_Item_tags_1)
		/sizeof(asn_DEF_DRBs_ToBeSetupMod_Item_tags_1[0]), /* 1 */
	asn_DEF_DRBs_ToBeSetupMod_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_DRBs_ToBeSetupMod_Item_tags_1)
		/sizeof(asn_DEF_DRBs_ToBeSetupMod_Item_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DRBs_ToBeSetupMod_Item_1,
	7,	/* Elements count */
	&asn_SPC_DRBs_ToBeSetupMod_Item_specs_1	/* Additional specs */
};

