/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "/root/svaidhya/ASN1_file/F1.asn1"
 * 	`asn1c -pdu=all -fno-include-deps -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D /root/svaidhya/28March_ASN1_l2/l2/src/codec_utils/F1AP/`
 */

#ifndef	_GNBDUOverloadInformation_H_
#define	_GNBDUOverloadInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GNBDUOverloadInformation {
	GNBDUOverloadInformation_overloaded	= 0,
	GNBDUOverloadInformation_not_overloaded	= 1
} e_GNBDUOverloadInformation;

/* GNBDUOverloadInformation */
typedef long	 GNBDUOverloadInformation_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_GNBDUOverloadInformation_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_GNBDUOverloadInformation;
extern const asn_INTEGER_specifics_t asn_SPC_GNBDUOverloadInformation_specs_1;
asn_struct_free_f GNBDUOverloadInformation_free;
asn_struct_print_f GNBDUOverloadInformation_print;
asn_constr_check_f GNBDUOverloadInformation_constraint;
xer_type_decoder_f GNBDUOverloadInformation_decode_xer;
xer_type_encoder_f GNBDUOverloadInformation_encode_xer;
per_type_decoder_f GNBDUOverloadInformation_decode_uper;
per_type_encoder_f GNBDUOverloadInformation_encode_uper;
per_type_decoder_f GNBDUOverloadInformation_decode_aper;
per_type_encoder_f GNBDUOverloadInformation_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _GNBDUOverloadInformation_H_ */
#include <asn_internal.h>
