/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1.asn1"
 * 	`asn1c -D ./out -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-example`
 */

#ifndef	_GNBDUOverloadInformation_H_
#define	_GNBDUOverloadInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GNBDUOverloadInformation {
	GNBDUOverloadInformation_overloaded	= 0,
	GNBDUOverloadInformation_not_overloaded	= 1
} e_GNBDUOverloadInformation;

/* GNBDUOverloadInformation */
typedef long	 GNBDUOverloadInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GNBDUOverloadInformation;
asn_struct_free_f GNBDUOverloadInformation_free;
asn_struct_print_f GNBDUOverloadInformation_print;
asn_constr_check_f GNBDUOverloadInformation_constraint;
ber_type_decoder_f GNBDUOverloadInformation_decode_ber;
der_type_encoder_f GNBDUOverloadInformation_encode_der;
xer_type_decoder_f GNBDUOverloadInformation_decode_xer;
xer_type_encoder_f GNBDUOverloadInformation_encode_xer;
oer_type_decoder_f GNBDUOverloadInformation_decode_oer;
oer_type_encoder_f GNBDUOverloadInformation_encode_oer;
per_type_decoder_f GNBDUOverloadInformation_decode_uper;
per_type_encoder_f GNBDUOverloadInformation_encode_uper;
per_type_decoder_f GNBDUOverloadInformation_decode_aper;
per_type_encoder_f GNBDUOverloadInformation_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _GNBDUOverloadInformation_H_ */
#include <asn_internal.h>
