/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1.asn1"
 * 	`asn1c -D ./out -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-example`
 */

#ifndef	_Latest_RRC_Version_Enhanced_H_
#define	_Latest_RRC_Version_Enhanced_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Latest-RRC-Version-Enhanced */
typedef OCTET_STRING_t	 Latest_RRC_Version_Enhanced_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Latest_RRC_Version_Enhanced;
asn_struct_free_f Latest_RRC_Version_Enhanced_free;
asn_struct_print_f Latest_RRC_Version_Enhanced_print;
asn_constr_check_f Latest_RRC_Version_Enhanced_constraint;
ber_type_decoder_f Latest_RRC_Version_Enhanced_decode_ber;
der_type_encoder_f Latest_RRC_Version_Enhanced_encode_der;
xer_type_decoder_f Latest_RRC_Version_Enhanced_decode_xer;
xer_type_encoder_f Latest_RRC_Version_Enhanced_encode_xer;
oer_type_decoder_f Latest_RRC_Version_Enhanced_decode_oer;
oer_type_encoder_f Latest_RRC_Version_Enhanced_encode_oer;
per_type_decoder_f Latest_RRC_Version_Enhanced_decode_uper;
per_type_encoder_f Latest_RRC_Version_Enhanced_encode_uper;
per_type_decoder_f Latest_RRC_Version_Enhanced_decode_aper;
per_type_encoder_f Latest_RRC_Version_Enhanced_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Latest_RRC_Version_Enhanced_H_ */
#include <asn_internal.h>
