/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1.asn1"
 * 	`asn1c -D ./out -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-example`
 */

#include "Protected-EUTRA-Resources-Item.h"

#include "ProtocolExtensionContainer.h"
static asn_TYPE_member_t asn_MBR_Protected_EUTRA_Resources_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Protected_EUTRA_Resources_Item, spectrumSharingGroupID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SpectrumSharingGroupID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"spectrumSharingGroupID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Protected_EUTRA_Resources_Item, eUTRACells_List),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EUTRACells_List,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eUTRACells-List"
		},
	{ ATF_POINTER, 1, offsetof(struct Protected_EUTRA_Resources_Item, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_4624P70,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_Protected_EUTRA_Resources_Item_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_Protected_EUTRA_Resources_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Protected_EUTRA_Resources_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* spectrumSharingGroupID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* eUTRACells-List */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_Protected_EUTRA_Resources_Item_specs_1 = {
	sizeof(struct Protected_EUTRA_Resources_Item),
	offsetof(struct Protected_EUTRA_Resources_Item, _asn_ctx),
	asn_MAP_Protected_EUTRA_Resources_Item_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_Protected_EUTRA_Resources_Item_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Protected_EUTRA_Resources_Item = {
	"Protected-EUTRA-Resources-Item",
	"Protected-EUTRA-Resources-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_Protected_EUTRA_Resources_Item_tags_1,
	sizeof(asn_DEF_Protected_EUTRA_Resources_Item_tags_1)
		/sizeof(asn_DEF_Protected_EUTRA_Resources_Item_tags_1[0]), /* 1 */
	asn_DEF_Protected_EUTRA_Resources_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_Protected_EUTRA_Resources_Item_tags_1)
		/sizeof(asn_DEF_Protected_EUTRA_Resources_Item_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Protected_EUTRA_Resources_Item_1,
	3,	/* Elements count */
	&asn_SPC_Protected_EUTRA_Resources_Item_specs_1	/* Additional specs */
};

