/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-Containers"
 * 	found in "F1.asn1"
 * 	`asn1c -D ./out -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-example`
 */

#ifndef	_ProtocolIE_Container_H_
#define	_ProtocolIE_Container_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ResetIEs;
struct ResetAcknowledgeIEs;
struct ErrorIndicationIEs;
struct F1SetupRequestIEs;
struct F1SetupResponseIEs;
struct F1SetupFailureIEs;
struct GNBDUConfigurationUpdateIEs;
struct GNBDUConfigurationUpdateAcknowledgeIEs;
struct GNBDUConfigurationUpdateFailureIEs;
struct GNBCUConfigurationUpdateIEs;
struct GNBCUConfigurationUpdateAcknowledgeIEs;
struct GNBCUConfigurationUpdateFailureIEs;
struct GNBDUResourceCoordinationRequest_IEs;
struct GNBDUResourceCoordinationResponse_IEs;
struct UEContextSetupRequestIEs;
struct UEContextSetupResponseIEs;
struct UEContextSetupFailureIEs;
struct UEContextReleaseRequestIEs;
struct UEContextReleaseCommandIEs;
struct UEContextReleaseCompleteIEs;
struct UEContextModificationRequestIEs;
struct UEContextModificationResponseIEs;
struct UEContextModificationFailureIEs;
struct UEContextModificationRequiredIEs;
struct UEContextModificationConfirmIEs;
struct UEContextModificationRefuseIEs;
struct WriteReplaceWarningRequestIEs;
struct WriteReplaceWarningResponseIEs;
struct PWSCancelRequestIEs;
struct PWSCancelResponseIEs;
struct UEInactivityNotificationIEs;
struct InitialULRRCMessageTransferIEs;
struct DLRRCMessageTransferIEs;
struct ULRRCMessageTransferIEs;
struct SystemInformationDeliveryCommandIEs;
struct PagingIEs;
struct NotifyIEs;
struct PWSRestartIndicationIEs;
struct PWSFailureIndicationIEs;
struct GNBDUStatusIndicationIEs;
struct RRCDeliveryReportIEs;

/* ProtocolIE-Container */
typedef struct ProtocolIE_Container_4587P0 {
	A_SEQUENCE_OF(struct ResetIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P0_t;
typedef struct ProtocolIE_Container_4587P1 {
	A_SEQUENCE_OF(struct ResetAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P1_t;
typedef struct ProtocolIE_Container_4587P2 {
	A_SEQUENCE_OF(struct ErrorIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P2_t;
typedef struct ProtocolIE_Container_4587P3 {
	A_SEQUENCE_OF(struct F1SetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P3_t;
typedef struct ProtocolIE_Container_4587P4 {
	A_SEQUENCE_OF(struct F1SetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P4_t;
typedef struct ProtocolIE_Container_4587P5 {
	A_SEQUENCE_OF(struct F1SetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P5_t;
typedef struct ProtocolIE_Container_4587P6 {
	A_SEQUENCE_OF(struct GNBDUConfigurationUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P6_t;
typedef struct ProtocolIE_Container_4587P7 {
	A_SEQUENCE_OF(struct GNBDUConfigurationUpdateAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P7_t;
typedef struct ProtocolIE_Container_4587P8 {
	A_SEQUENCE_OF(struct GNBDUConfigurationUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P8_t;
typedef struct ProtocolIE_Container_4587P9 {
	A_SEQUENCE_OF(struct GNBCUConfigurationUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P9_t;
typedef struct ProtocolIE_Container_4587P10 {
	A_SEQUENCE_OF(struct GNBCUConfigurationUpdateAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P10_t;
typedef struct ProtocolIE_Container_4587P11 {
	A_SEQUENCE_OF(struct GNBCUConfigurationUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P11_t;
typedef struct ProtocolIE_Container_4587P12 {
	A_SEQUENCE_OF(struct GNBDUResourceCoordinationRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P12_t;
typedef struct ProtocolIE_Container_4587P13 {
	A_SEQUENCE_OF(struct GNBDUResourceCoordinationResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P13_t;
typedef struct ProtocolIE_Container_4587P14 {
	A_SEQUENCE_OF(struct UEContextSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P14_t;
typedef struct ProtocolIE_Container_4587P15 {
	A_SEQUENCE_OF(struct UEContextSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P15_t;
typedef struct ProtocolIE_Container_4587P16 {
	A_SEQUENCE_OF(struct UEContextSetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P16_t;
typedef struct ProtocolIE_Container_4587P17 {
	A_SEQUENCE_OF(struct UEContextReleaseRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P17_t;
typedef struct ProtocolIE_Container_4587P18 {
	A_SEQUENCE_OF(struct UEContextReleaseCommandIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P18_t;
typedef struct ProtocolIE_Container_4587P19 {
	A_SEQUENCE_OF(struct UEContextReleaseCompleteIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P19_t;
typedef struct ProtocolIE_Container_4587P20 {
	A_SEQUENCE_OF(struct UEContextModificationRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P20_t;
typedef struct ProtocolIE_Container_4587P21 {
	A_SEQUENCE_OF(struct UEContextModificationResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P21_t;
typedef struct ProtocolIE_Container_4587P22 {
	A_SEQUENCE_OF(struct UEContextModificationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P22_t;
typedef struct ProtocolIE_Container_4587P23 {
	A_SEQUENCE_OF(struct UEContextModificationRequiredIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P23_t;
typedef struct ProtocolIE_Container_4587P24 {
	A_SEQUENCE_OF(struct UEContextModificationConfirmIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P24_t;
typedef struct ProtocolIE_Container_4587P25 {
	A_SEQUENCE_OF(struct UEContextModificationRefuseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P25_t;
typedef struct ProtocolIE_Container_4587P26 {
	A_SEQUENCE_OF(struct WriteReplaceWarningRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P26_t;
typedef struct ProtocolIE_Container_4587P27 {
	A_SEQUENCE_OF(struct WriteReplaceWarningResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P27_t;
typedef struct ProtocolIE_Container_4587P28 {
	A_SEQUENCE_OF(struct PWSCancelRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P28_t;
typedef struct ProtocolIE_Container_4587P29 {
	A_SEQUENCE_OF(struct PWSCancelResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P29_t;
typedef struct ProtocolIE_Container_4587P30 {
	A_SEQUENCE_OF(struct UEInactivityNotificationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P30_t;
typedef struct ProtocolIE_Container_4587P31 {
	A_SEQUENCE_OF(struct InitialULRRCMessageTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P31_t;
typedef struct ProtocolIE_Container_4587P32 {
	A_SEQUENCE_OF(struct DLRRCMessageTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P32_t;
typedef struct ProtocolIE_Container_4587P33 {
	A_SEQUENCE_OF(struct ULRRCMessageTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P33_t;
typedef struct ProtocolIE_Container_4587P34 {
	A_SEQUENCE_OF(struct SystemInformationDeliveryCommandIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P34_t;
typedef struct ProtocolIE_Container_4587P35 {
	A_SEQUENCE_OF(struct PagingIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P35_t;
typedef struct ProtocolIE_Container_4587P36 {
	A_SEQUENCE_OF(struct NotifyIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P36_t;
typedef struct ProtocolIE_Container_4587P37 {
	A_SEQUENCE_OF(struct PWSRestartIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P37_t;
typedef struct ProtocolIE_Container_4587P38 {
	A_SEQUENCE_OF(struct PWSFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P38_t;
typedef struct ProtocolIE_Container_4587P39 {
	A_SEQUENCE_OF(struct GNBDUStatusIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P39_t;
typedef struct ProtocolIE_Container_4587P40 {
	A_SEQUENCE_OF(struct RRCDeliveryReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_4587P40_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P0;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P0_1[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P1;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P1_specs_3;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P1_3[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P2;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P2_specs_5;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P2_5[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P3;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P3_specs_7;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P3_7[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P4;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P4_specs_9;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P4_9[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P5;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P5_specs_11;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P5_11[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P6;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P6_specs_13;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P6_13[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P7;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P7_specs_15;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P7_15[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P8;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P8_specs_17;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P8_17[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P9;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P9_specs_19;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P9_19[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P10;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P10_specs_21;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P10_21[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P11;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P11_specs_23;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P11_23[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P12;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P12_specs_25;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P12_25[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P13;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P13_specs_27;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P13_27[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P14;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P14_specs_29;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P14_29[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P15;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P15_specs_31;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P15_31[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P16;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P16_specs_33;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P16_33[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P17;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P17_specs_35;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P17_35[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P18;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P18_specs_37;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P18_37[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P19;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P19_specs_39;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P19_39[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P20;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P20_specs_41;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P20_41[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P21;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P21_specs_43;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P21_43[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P22;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P22_specs_45;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P22_45[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P23;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P23_specs_47;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P23_47[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P24;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P24_specs_49;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P24_49[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P25;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P25_specs_51;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P25_51[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P26;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P26_specs_53;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P26_53[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P27;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P27_specs_55;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P27_55[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P28;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P28_specs_57;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P28_57[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P29;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P29_specs_59;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P29_59[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P30;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P30_specs_61;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P30_61[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P31;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P31_specs_63;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P31_63[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P32;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P32_specs_65;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P32_65[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P33;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P33_specs_67;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P33_67[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P34;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P34_specs_69;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P34_69[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P35;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P35_specs_71;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P35_71[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P36;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P36_specs_73;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P36_73[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P37;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P37_specs_75;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P37_75[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P38;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P38_specs_77;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P38_77[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P39;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P39_specs_79;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P39_79[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_4587P40;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_4587P40_specs_81;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_4587P40_81[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_4587P40_constr_81;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_Container_H_ */
#include <asn_internal.h>
