/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1.asn1"
 * 	`asn1c -D ./out -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-example`
 */

#ifndef	_QoS_Characteristics_H_
#define	_QoS_Characteristics_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>
#include "NonDynamic5QIDescriptor.h"
#include "Dynamic5QIDescriptor.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum QoS_Characteristics_PR {
	QoS_Characteristics_PR_NOTHING,	/* No components present */
	QoS_Characteristics_PR_non_Dynamic_5QI,
	QoS_Characteristics_PR_dynamic_5QI,
	QoS_Characteristics_PR_choice_extension
} QoS_Characteristics_PR;

/* Forward declarations */
struct NonDynamic5QIDescriptor;
struct Dynamic5QIDescriptor;
struct ProtocolIE_SingleContainer;

/* QoS-Characteristics */
typedef struct QoS_Characteristics {
	QoS_Characteristics_PR present;
	union QoS_Characteristics_u {
		NonDynamic5QIDescriptor_t	*non_Dynamic_5QI;
		Dynamic5QIDescriptor_t	*dynamic_5QI;
		struct ProtocolIE_SingleContainer	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} QoS_Characteristics_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QoS_Characteristics;
extern asn_CHOICE_specifics_t asn_SPC_QoS_Characteristics_specs_1;
extern asn_TYPE_member_t asn_MBR_QoS_Characteristics_1[3];
extern asn_per_constraints_t asn_PER_type_QoS_Characteristics_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _QoS_Characteristics_H_ */
#include <asn_internal.h>
