/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1.asn1"
 * 	`asn1c -D ./out -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-example`
 */

#ifndef	_SpectrumSharingGroupID_H_
#define	_SpectrumSharingGroupID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SpectrumSharingGroupID */
typedef long	 SpectrumSharingGroupID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SpectrumSharingGroupID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SpectrumSharingGroupID;
asn_struct_free_f SpectrumSharingGroupID_free;
asn_struct_print_f SpectrumSharingGroupID_print;
asn_constr_check_f SpectrumSharingGroupID_constraint;
ber_type_decoder_f SpectrumSharingGroupID_decode_ber;
der_type_encoder_f SpectrumSharingGroupID_encode_der;
xer_type_decoder_f SpectrumSharingGroupID_decode_xer;
xer_type_encoder_f SpectrumSharingGroupID_encode_xer;
oer_type_decoder_f SpectrumSharingGroupID_decode_oer;
oer_type_encoder_f SpectrumSharingGroupID_encode_oer;
per_type_decoder_f SpectrumSharingGroupID_decode_uper;
per_type_encoder_f SpectrumSharingGroupID_encode_uper;
per_type_decoder_f SpectrumSharingGroupID_decode_aper;
per_type_encoder_f SpectrumSharingGroupID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SpectrumSharingGroupID_H_ */
#include <asn_internal.h>
