/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1.asn1"
 * 	`asn1c -D ./out -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-example`
 */

#ifndef	_UPTransportLayerInformation_H_
#define	_UPTransportLayerInformation_H_


#include <asn_application.h>
#include "GTPTunnel.h"
/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UPTransportLayerInformation_PR {
	UPTransportLayerInformation_PR_NOTHING,	/* No components present */
	UPTransportLayerInformation_PR_gTPTunnel,
	UPTransportLayerInformation_PR_choice_extension
} UPTransportLayerInformation_PR;

/* Forward declarations */
struct GTPTunnel;
struct ProtocolIE_SingleContainer;

/* UPTransportLayerInformation */
typedef struct UPTransportLayerInformation {
	UPTransportLayerInformation_PR present;
	union UPTransportLayerInformation_u {
		struct GTPTunnel	*gTPTunnel;
		struct ProtocolIE_SingleContainer	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UPTransportLayerInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UPTransportLayerInformation;
extern asn_CHOICE_specifics_t asn_SPC_UPTransportLayerInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_UPTransportLayerInformation_1[2];
extern asn_per_constraints_t asn_PER_type_UPTransportLayerInformation_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _UPTransportLayerInformation_H_ */
#include <asn_internal.h>
