/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-CommonDataTypes"
 * 	found in "2022_E2AP.asn1"
 * 	`asn1c -D ./E2AP/ -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-example`
 */

#ifndef	_ProtocolIE_IDE2_H_
#define	_ProtocolIE_IDE2_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProtocolIE-IDE2 */
typedef long	 ProtocolIE_IDE2_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ProtocolIE_IDE2_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_IDE2;
asn_struct_free_f ProtocolIE_IDE2_free;
asn_struct_print_f ProtocolIE_IDE2_print;
asn_constr_check_f ProtocolIE_IDE2_constraint;
ber_type_decoder_f ProtocolIE_IDE2_decode_ber;
der_type_encoder_f ProtocolIE_IDE2_encode_der;
xer_type_decoder_f ProtocolIE_IDE2_decode_xer;
xer_type_encoder_f ProtocolIE_IDE2_encode_xer;
oer_type_decoder_f ProtocolIE_IDE2_decode_oer;
oer_type_encoder_f ProtocolIE_IDE2_encode_oer;
per_type_decoder_f ProtocolIE_IDE2_decode_uper;
per_type_encoder_f ProtocolIE_IDE2_encode_uper;
per_type_decoder_f ProtocolIE_IDE2_decode_aper;
per_type_encoder_f ProtocolIE_IDE2_encode_aper;
#define ProtocolIE_IDE2_id_CauseE2	((ProtocolIE_IDE2_t)1)
#define ProtocolIE_IDE2_id_CriticalityDiagnosticsE2	((ProtocolIE_IDE2_t)2)
#define ProtocolIE_IDE2_id_GlobalE2node_ID	((ProtocolIE_IDE2_t)3)
#define ProtocolIE_IDE2_id_GlobalRIC_ID	((ProtocolIE_IDE2_t)4)
#define ProtocolIE_IDE2_id_RANfunctionID	((ProtocolIE_IDE2_t)5)
#define ProtocolIE_IDE2_id_RANfunctionID_Item	((ProtocolIE_IDE2_t)6)
#define ProtocolIE_IDE2_id_RANfunctionIEcause_Item	((ProtocolIE_IDE2_t)7)
#define ProtocolIE_IDE2_id_RANfunction_Item	((ProtocolIE_IDE2_t)8)
#define ProtocolIE_IDE2_id_RANfunctionsAccepted	((ProtocolIE_IDE2_t)9)
#define ProtocolIE_IDE2_id_RANfunctionsAdded	((ProtocolIE_IDE2_t)10)
#define ProtocolIE_IDE2_id_RANfunctionsDeleted	((ProtocolIE_IDE2_t)11)
#define ProtocolIE_IDE2_id_RANfunctionsModified	((ProtocolIE_IDE2_t)12)
#define ProtocolIE_IDE2_id_RANfunctionsRejected	((ProtocolIE_IDE2_t)13)
#define ProtocolIE_IDE2_id_RICaction_Admitted_Item	((ProtocolIE_IDE2_t)14)
#define ProtocolIE_IDE2_id_RICactionID	((ProtocolIE_IDE2_t)15)
#define ProtocolIE_IDE2_id_RICaction_NotAdmitted_Item	((ProtocolIE_IDE2_t)16)
#define ProtocolIE_IDE2_id_RICactions_Admitted	((ProtocolIE_IDE2_t)17)
#define ProtocolIE_IDE2_id_RICactions_NotAdmitted	((ProtocolIE_IDE2_t)18)
#define ProtocolIE_IDE2_id_RICaction_ToBeSetup_Item	((ProtocolIE_IDE2_t)19)
#define ProtocolIE_IDE2_id_RICcallProcessID	((ProtocolIE_IDE2_t)20)
#define ProtocolIE_IDE2_id_RICcontrolAckRequest	((ProtocolIE_IDE2_t)21)
#define ProtocolIE_IDE2_id_RICcontrolHeader	((ProtocolIE_IDE2_t)22)
#define ProtocolIE_IDE2_id_RICcontrolMessage	((ProtocolIE_IDE2_t)23)
#define ProtocolIE_IDE2_id_RICcontrolStatus	((ProtocolIE_IDE2_t)24)
#define ProtocolIE_IDE2_id_RICindicationHeader	((ProtocolIE_IDE2_t)25)
#define ProtocolIE_IDE2_id_RICindicationMessage	((ProtocolIE_IDE2_t)26)
#define ProtocolIE_IDE2_id_RICindicationSN	((ProtocolIE_IDE2_t)27)
#define ProtocolIE_IDE2_id_RICindicationType	((ProtocolIE_IDE2_t)28)
#define ProtocolIE_IDE2_id_RICrequestID	((ProtocolIE_IDE2_t)29)
#define ProtocolIE_IDE2_id_RICsubscriptionDetails	((ProtocolIE_IDE2_t)30)
#define ProtocolIE_IDE2_id_TimeToWaitE2	((ProtocolIE_IDE2_t)31)
#define ProtocolIE_IDE2_id_RICcontrolOutcome	((ProtocolIE_IDE2_t)32)
#define ProtocolIE_IDE2_id_E2nodeComponentConfigUpdate	((ProtocolIE_IDE2_t)33)
#define ProtocolIE_IDE2_id_E2nodeComponentConfigUpdate_Item	((ProtocolIE_IDE2_t)34)
#define ProtocolIE_IDE2_id_E2nodeComponentConfigUpdateAck	((ProtocolIE_IDE2_t)35)
#define ProtocolIE_IDE2_id_E2nodeComponentConfigUpdateAck_Item	((ProtocolIE_IDE2_t)36)
#define ProtocolIE_IDE2_id_E2connectionSetup	((ProtocolIE_IDE2_t)39)
#define ProtocolIE_IDE2_id_E2connectionSetupFailed	((ProtocolIE_IDE2_t)40)
#define ProtocolIE_IDE2_id_E2connectionSetupFailed_Item	((ProtocolIE_IDE2_t)41)
#define ProtocolIE_IDE2_id_E2connectionFailed_Item	((ProtocolIE_IDE2_t)42)
#define ProtocolIE_IDE2_id_E2connectionUpdate_Item	((ProtocolIE_IDE2_t)43)
#define ProtocolIE_IDE2_id_E2connectionUpdateAdd	((ProtocolIE_IDE2_t)44)
#define ProtocolIE_IDE2_id_E2connectionUpdateModify	((ProtocolIE_IDE2_t)45)
#define ProtocolIE_IDE2_id_E2connectionUpdateRemove	((ProtocolIE_IDE2_t)46)
#define ProtocolIE_IDE2_id_E2connectionUpdateRemove_Item	((ProtocolIE_IDE2_t)47)
#define ProtocolIE_IDE2_id_TNLinformation	((ProtocolIE_IDE2_t)48)
#define ProtocolIE_IDE2_id_TransactionID	((ProtocolIE_IDE2_t)49)
#define ProtocolIE_IDE2_id_E2nodeComponentConfigAddition	((ProtocolIE_IDE2_t)50)
#define ProtocolIE_IDE2_id_E2nodeComponentConfigAddition_Item	((ProtocolIE_IDE2_t)51)
#define ProtocolIE_IDE2_id_E2nodeComponentConfigAdditionAck	((ProtocolIE_IDE2_t)52)
#define ProtocolIE_IDE2_id_E2nodeComponentConfigAdditionAck_Item	((ProtocolIE_IDE2_t)53)
#define ProtocolIE_IDE2_id_E2nodeComponentConfigRemoval	((ProtocolIE_IDE2_t)54)
#define ProtocolIE_IDE2_id_E2nodeComponentConfigRemoval_Item	((ProtocolIE_IDE2_t)55)
#define ProtocolIE_IDE2_id_E2nodeComponentConfigRemovalAck	((ProtocolIE_IDE2_t)56)
#define ProtocolIE_IDE2_id_E2nodeComponentConfigRemovalAck_Item	((ProtocolIE_IDE2_t)57)
#define ProtocolIE_IDE2_id_E2nodeTNLassociationRemoval	((ProtocolIE_IDE2_t)58)
#define ProtocolIE_IDE2_id_E2nodeTNLassociationRemoval_Item	((ProtocolIE_IDE2_t)59)
#define ProtocolIE_IDE2_id_RICsubscriptionToBeRemoved	((ProtocolIE_IDE2_t)50)
#define ProtocolIE_IDE2_id_RICsubscription_withCause_Item	((ProtocolIE_IDE2_t)51)

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_IDE2_H_ */
#include <asn_internal.h>
