/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "../../ASN1_Input/E2APV0300.asn1"
 * 	`asn1c -D ../../E2_v3.0_output/ -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-example`
 */

#ifndef	_RICqueryDefinition_H_
#define	_RICqueryDefinition_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RICqueryDefinition */
typedef OCTET_STRING_t	 RICqueryDefinition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RICqueryDefinition;
asn_struct_free_f RICqueryDefinition_free;
asn_struct_print_f RICqueryDefinition_print;
asn_constr_check_f RICqueryDefinition_constraint;
ber_type_decoder_f RICqueryDefinition_decode_ber;
der_type_encoder_f RICqueryDefinition_encode_der;
xer_type_decoder_f RICqueryDefinition_decode_xer;
xer_type_encoder_f RICqueryDefinition_encode_xer;
oer_type_decoder_f RICqueryDefinition_decode_oer;
oer_type_encoder_f RICqueryDefinition_encode_oer;
per_type_decoder_f RICqueryDefinition_decode_uper;
per_type_encoder_f RICqueryDefinition_encode_uper;
per_type_decoder_f RICqueryDefinition_decode_aper;
per_type_encoder_f RICqueryDefinition_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RICqueryDefinition_H_ */
#include <asn_internal.h>
