/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "/root/svaidhya/ASN1_file/E2APV0300.asn1"
 * 	`asn1c -fno-include-deps -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D /root/svaidhya/28March_ASN1_l2/l2/src/codec_utils/E2AP/`
 */

#ifndef	_RICsubsequentAction_H_
#define	_RICsubsequentAction_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RICsubsequentActionType.h"
#include "RICtimeToWait.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RICsubsequentAction */
typedef struct RICsubsequentAction {
	RICsubsequentActionType_t	 ricSubsequentActionType;
	RICtimeToWait_t	 ricTimeToWait;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RICsubsequentAction_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RICsubsequentAction;
extern asn_SEQUENCE_specifics_t asn_SPC_RICsubsequentAction_specs_1;
extern asn_TYPE_member_t asn_MBR_RICsubsequentAction_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RICsubsequentAction_H_ */
#include <asn_internal.h>
