/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Descriptions"
 * 	found in "../../ASN1_Input/E2APV0300.asn1"
 * 	`asn1c -D ../../E2_v3.0_output/ -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-example`
 */

#ifndef	_SuccessfulOutcomeE2_H_
#define	_SuccessfulOutcomeE2_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProcedureCodeE2.h"
#include "CriticalityE2.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "RICsubscriptionRequest.h"
#include "RICsubscriptionResponse.h"
#include "RICsubscriptionFailure.h"
#include "RICsubscriptionDeleteRequest.h"
#include "RICsubscriptionDeleteResponse.h"
#include "RICsubscriptionDeleteFailure.h"
#include "RICsubscriptionModificationRequest.h"
#include "RICsubscriptionModificationResponse.h"
#include "RICsubscriptionModificationFailure.h"
#include "RICsubscriptionModificationRequired.h"
#include "RICsubscriptionModificationConfirm.h"
#include "RICsubscriptionModificationRefuse.h"
#include "RICQueryRequest.h"
#include "RICQueryResponse.h"
#include "RICQueryFailure.h"
#include "RICserviceUpdate.h"
#include "RICserviceUpdateAcknowledge.h"
#include "RICserviceUpdateFailure.h"
#include "RICcontrolRequest.h"
#include "RICcontrolAcknowledge.h"
#include "RICcontrolFailure.h"
#include "E2setupRequest.h"
#include "E2setupResponse.h"
#include "E2setupFailure.h"
#include "E2nodeConfigurationUpdate.h"
#include "E2nodeConfigurationUpdateAcknowledge.h"
#include "E2nodeConfigurationUpdateFailure.h"
#include "E2connectionUpdate.h"
#include "E2connectionUpdateAcknowledge.h"
#include "E2connectionUpdateFailure.h"
#include "ResetRequestE2.h"
#include "ResetResponseE2.h"
#include "E2RemovalRequest.h"
#include "E2RemovalResponse.h"
#include "E2RemovalFailure.h"
#include "RICindication.h"
#include "RICserviceQuery.h"
#include "ErrorIndicationE2.h"
#include "RICsubscriptionDeleteRequired.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SuccessfulOutcomeE2__value_PR {
	SuccessfulOutcomeE2__value_PR_NOTHING,	/* No components present */
	SuccessfulOutcomeE2__value_PR_RICsubscriptionResponse,
	SuccessfulOutcomeE2__value_PR_RICsubscriptionDeleteResponse,
	SuccessfulOutcomeE2__value_PR_RICsubscriptionModificationResponse,
	SuccessfulOutcomeE2__value_PR_RICsubscriptionModificationConfirm,
	SuccessfulOutcomeE2__value_PR_RICQueryResponse,
	SuccessfulOutcomeE2__value_PR_RICserviceUpdateAcknowledge,
	SuccessfulOutcomeE2__value_PR_RICcontrolAcknowledge,
	SuccessfulOutcomeE2__value_PR_E2setupResponse,
	SuccessfulOutcomeE2__value_PR_E2nodeConfigurationUpdateAcknowledge,
	SuccessfulOutcomeE2__value_PR_E2connectionUpdateAcknowledge,
	SuccessfulOutcomeE2__value_PR_ResetResponseE2,
	SuccessfulOutcomeE2__value_PR_E2RemovalResponse
} SuccessfulOutcomeE2__value_PR;

/* SuccessfulOutcomeE2 */
typedef struct SuccessfulOutcomeE2 {
	ProcedureCodeE2_t	 procedureCode;
	CriticalityE2_t	 criticality;
	struct SuccessfulOutcomeE2__value {
		SuccessfulOutcomeE2__value_PR present;
		union SuccessfulOutcomeE2__value_u {
			RICsubscriptionResponse_t	 RICsubscriptionResponse;
			RICsubscriptionDeleteResponse_t	 RICsubscriptionDeleteResponse;
			RICsubscriptionModificationResponse_t	 RICsubscriptionModificationResponse;
			RICsubscriptionModificationConfirm_t	 RICsubscriptionModificationConfirm;
			RICQueryResponse_t	 RICQueryResponse;
			RICserviceUpdateAcknowledge_t	 RICserviceUpdateAcknowledge;
			RICcontrolAcknowledge_t	 RICcontrolAcknowledge;
			E2setupResponse_t	 E2setupResponse;
			E2nodeConfigurationUpdateAcknowledge_t	 E2nodeConfigurationUpdateAcknowledge;
			E2connectionUpdateAcknowledge_t	 E2connectionUpdateAcknowledge;
			ResetResponseE2_t	 ResetResponseE2;
			E2RemovalResponse_t	 E2RemovalResponse;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SuccessfulOutcomeE2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SuccessfulOutcomeE2;
extern asn_SEQUENCE_specifics_t asn_SPC_SuccessfulOutcomeE2_specs_1;
extern asn_TYPE_member_t asn_MBR_SuccessfulOutcomeE2_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SuccessfulOutcomeE2_H_ */
#include <asn_internal.h>
