apiVersion: v1
kind: Service
metadata:
  name: {{ include "du.fullname" . }}
  labels:
    {{- include "du.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol:  {{ .Values.service.protocol }}
      name: f1ap
  selector:
    {{- include "du.selectorLabels" . | nindent 4 }}
