/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-InterNodeDefinitions"
 * 	found in "/root/svaidhya/ASN1_file/rrc_15_3.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D /root/svaidhya/28March_ASN1_l2/l2/src/codec_utils/RRC/`
 */

#ifndef	_CG_ConfigInfoRrc_H_
#define	_CG_ConfigInfoRrc_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CG_ConfigInfoRrc__criticalExtensions_PR {
	CG_ConfigInfoRrc__criticalExtensions_PR_NOTHING,	/* No components present */
	CG_ConfigInfoRrc__criticalExtensions_PR_c1,
	CG_ConfigInfoRrc__criticalExtensions_PR_criticalExtensionsFuture
} CG_ConfigInfoRrc__criticalExtensions_PR;
typedef enum CG_ConfigInfoRrc__criticalExtensions__c1_PR {
	CG_ConfigInfoRrc__criticalExtensions__c1_PR_NOTHING,	/* No components present */
	CG_ConfigInfoRrc__criticalExtensions__c1_PR_cg_ConfigInfo,
	CG_ConfigInfoRrc__criticalExtensions__c1_PR_spare3,
	CG_ConfigInfoRrc__criticalExtensions__c1_PR_spare2,
	CG_ConfigInfoRrc__criticalExtensions__c1_PR_spare1
} CG_ConfigInfoRrc__criticalExtensions__c1_PR;

/* Forward declarations */
struct CG_ConfigInfo_IEs;

/* CG-ConfigInfoRrc */
typedef struct CG_ConfigInfoRrc {
	struct CG_ConfigInfoRrc__criticalExtensions {
		CG_ConfigInfoRrc__criticalExtensions_PR present;
		union CG_ConfigInfoRrc__criticalExtensions_u {
			struct CG_ConfigInfoRrc__criticalExtensions__c1 {
				CG_ConfigInfoRrc__criticalExtensions__c1_PR present;
				union CG_ConfigInfoRrc__criticalExtensions__c1_u {
					struct CG_ConfigInfo_IEs	*cg_ConfigInfo;
					NULL_t	 spare3;
					NULL_t	 spare2;
					NULL_t	 spare1;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *c1;
			struct CG_ConfigInfoRrc__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CG_ConfigInfoRrc_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CG_ConfigInfoRrc;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CG-ConfigInfo-IEs.h"

#endif	/* _CG_ConfigInfoRrc_H_ */
#include <asn_internal.h>
