/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-InterNodeDefinitions"
 * 	found in "/home/labadmin/hlal/rrc_15.3_asn.asn1"
 * 	`asn1c -D ./15_3_rrc/ -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-example`
 */

#include "MeasConfigMN.h"

#include "NR-FreqInfo.h"
#include "GapConfig.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_measuredFrequenciesMN_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 32)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_measuredFrequenciesMN_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..32)) */};
static asn_per_constraints_t asn_PER_type_measuredFrequenciesMN_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 5,  5,  1,  32 }	/* (SIZE(1..32)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_measGapConfig_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_measGapConfig_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_gapPurpose_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_gapPurpose_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_measuredFrequenciesMN_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..32)) */};
static asn_per_constraints_t asn_PER_memb_measuredFrequenciesMN_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 5,  5,  1,  32 }	/* (SIZE(1..32)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_measuredFrequenciesMN_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NR_FreqInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_measuredFrequenciesMN_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_measuredFrequenciesMN_specs_2 = {
	sizeof(struct MeasConfigMN__measuredFrequenciesMN),
	offsetof(struct MeasConfigMN__measuredFrequenciesMN, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_measuredFrequenciesMN_2 = {
	"measuredFrequenciesMN",
	"measuredFrequenciesMN",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_measuredFrequenciesMN_tags_2,
	sizeof(asn_DEF_measuredFrequenciesMN_tags_2)
		/sizeof(asn_DEF_measuredFrequenciesMN_tags_2[0]) - 1, /* 1 */
	asn_DEF_measuredFrequenciesMN_tags_2,	/* Same as above */
	sizeof(asn_DEF_measuredFrequenciesMN_tags_2)
		/sizeof(asn_DEF_measuredFrequenciesMN_tags_2[0]), /* 2 */
	{ &asn_OER_type_measuredFrequenciesMN_constr_2, &asn_PER_type_measuredFrequenciesMN_constr_2, SEQUENCE_OF_constraint },
	asn_MBR_measuredFrequenciesMN_2,
	1,	/* Single element */
	&asn_SPC_measuredFrequenciesMN_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_measGapConfig_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasConfigMN__measGapConfig, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"release"
		},
	{ ATF_POINTER, 0, offsetof(struct MeasConfigMN__measGapConfig, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GapConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_measGapConfig_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_measGapConfig_specs_4 = {
	sizeof(struct MeasConfigMN__measGapConfig),
	offsetof(struct MeasConfigMN__measGapConfig, _asn_ctx),
	offsetof(struct MeasConfigMN__measGapConfig, present),
	sizeof(((struct MeasConfigMN__measGapConfig *)0)->present),
	asn_MAP_measGapConfig_tag2el_4,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_measGapConfig_4 = {
	"measGapConfig",
	"measGapConfig",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_measGapConfig_constr_4, &asn_PER_type_measGapConfig_constr_4, CHOICE_constraint },
	asn_MBR_measGapConfig_4,
	2,	/* Elements count */
	&asn_SPC_measGapConfig_specs_4	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_gapPurpose_value2enum_7[] = {
	{ 0,	5,	"perUE" },
	{ 1,	6,	"perFR1" }
};
static const unsigned int asn_MAP_gapPurpose_enum2value_7[] = {
	1,	/* perFR1(1) */
	0	/* perUE(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_gapPurpose_specs_7 = {
	asn_MAP_gapPurpose_value2enum_7,	/* "tag" => N; sorted by tag */
	asn_MAP_gapPurpose_enum2value_7,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_gapPurpose_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_gapPurpose_7 = {
	"gapPurpose",
	"gapPurpose",
	&asn_OP_NativeEnumerated,
	asn_DEF_gapPurpose_tags_7,
	sizeof(asn_DEF_gapPurpose_tags_7)
		/sizeof(asn_DEF_gapPurpose_tags_7[0]) - 1, /* 1 */
	asn_DEF_gapPurpose_tags_7,	/* Same as above */
	sizeof(asn_DEF_gapPurpose_tags_7)
		/sizeof(asn_DEF_gapPurpose_tags_7[0]), /* 2 */
	{ &asn_OER_type_gapPurpose_constr_7, &asn_PER_type_gapPurpose_constr_7, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_gapPurpose_specs_7	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_MeasConfigMN_1[] = {
	{ ATF_POINTER, 3, offsetof(struct MeasConfigMN, measuredFrequenciesMN),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_measuredFrequenciesMN_2,
		0,
		{ &asn_OER_memb_measuredFrequenciesMN_constr_2, &asn_PER_memb_measuredFrequenciesMN_constr_2,  memb_measuredFrequenciesMN_constraint_1 },
		0, 0, /* No default value */
		"measuredFrequenciesMN"
		},
	{ ATF_POINTER, 2, offsetof(struct MeasConfigMN, measGapConfig),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_measGapConfig_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measGapConfig"
		},
	{ ATF_POINTER, 1, offsetof(struct MeasConfigMN, gapPurpose),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_gapPurpose_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gapPurpose"
		},
};
static const int asn_MAP_MeasConfigMN_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_MeasConfigMN_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MeasConfigMN_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* measuredFrequenciesMN */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* measGapConfig */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* gapPurpose */
};
asn_SEQUENCE_specifics_t asn_SPC_MeasConfigMN_specs_1 = {
	sizeof(struct MeasConfigMN),
	offsetof(struct MeasConfigMN, _asn_ctx),
	asn_MAP_MeasConfigMN_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_MeasConfigMN_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MeasConfigMN = {
	"MeasConfigMN",
	"MeasConfigMN",
	&asn_OP_SEQUENCE,
	asn_DEF_MeasConfigMN_tags_1,
	sizeof(asn_DEF_MeasConfigMN_tags_1)
		/sizeof(asn_DEF_MeasConfigMN_tags_1[0]), /* 1 */
	asn_DEF_MeasConfigMN_tags_1,	/* Same as above */
	sizeof(asn_DEF_MeasConfigMN_tags_1)
		/sizeof(asn_DEF_MeasConfigMN_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MeasConfigMN_1,
	3,	/* Elements count */
	&asn_SPC_MeasConfigMN_specs_1	/* Additional specs */
};

