/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/root/svaidhya/ASN1_file/rrc_15_3.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D /root/svaidhya/28March_ASN1_l2/l2/src/codec_utils/RRC/`
 */

#ifndef	_SpCellConfig_H_
#define	_SpCellConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ServCellIndexRrc.h"
#include <NativeEnumerated.h>
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SpCellConfig__rlf_TimersAndConstants_PR {
	SpCellConfig__rlf_TimersAndConstants_PR_NOTHING,	/* No components present */
	SpCellConfig__rlf_TimersAndConstants_PR_release,
	SpCellConfig__rlf_TimersAndConstants_PR_setup
} SpCellConfig__rlf_TimersAndConstants_PR;
typedef enum SpCellConfig__rlmInSyncOutOfSyncThreshold {
	SpCellConfig__rlmInSyncOutOfSyncThreshold_n1	= 0
} e_SpCellConfig__rlmInSyncOutOfSyncThreshold;

/* Forward declarations */
struct ReconfigurationWithSync;
struct ServingCellConfig;
struct RLF_TimersAndConstants;

/* SpCellConfig */
typedef struct SpCellConfig {
	ServCellIndexRrc_t	*servCellIndex;	/* OPTIONAL */
	struct ReconfigurationWithSync	*reconfigurationWithSync;	/* OPTIONAL */
	struct SpCellConfig__rlf_TimersAndConstants {
		SpCellConfig__rlf_TimersAndConstants_PR present;
		union SpCellConfig__rlf_TimersAndConstants_u {
			NULL_t	 release;
			struct RLF_TimersAndConstants	*setup;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *rlf_TimersAndConstants;
	long	*rlmInSyncOutOfSyncThreshold;	/* OPTIONAL */
	struct ServingCellConfig	*spCellConfigDedicated;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SpCellConfig_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_rlmInSyncOutOfSyncThreshold_7;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SpCellConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_SpCellConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_SpCellConfig_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ReconfigurationWithSync.h"
#include "ServingCellConfig.h"
#include "RLF-TimersAndConstants.h"

#endif	/* _SpCellConfig_H_ */
#include <asn_internal.h>
