/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define maxPrivateIEs (65535)
#define maxProtocolExtensions (65535)
#define maxProtocolIEs (65535)
#define maxNRARFCN (3279165)
#define maxnoofErrors (256)
#define maxnoofIndividualF1ConnectionsToReset (65536)
#define maxCellingNBDU (512)
#define maxnoofSCells (32)
#define maxnoofSRBs (8)
#define maxnoofDRBs (64)
#define maxnoofULUPTNLInformation (2)
#define maxnoofDLUPTNLInformation (2)
#define maxnoofBPLMNs (6)
#define maxnoofCandidateSpCells (64)
#define maxnoofPotentialSpCells (64)
#define maxnoofNrCellBands (32)
#define maxnoofSIBTypes (32)
#define maxnoofSITypes (32)
#define maxnoofPagingCells (512)
#define maxnoofTNLAssociations (32)
#define maxnoofQoSFlows (64)
#define maxnoofSliceItems (1024)
#define maxCellineNB (256)
#define maxnoofExtendedBPLMNs (6)
#define maxnoofUEIDs (65536)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
