/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1.asn1"
 * 	`asn1c -D ./out -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-example`
 */

#ifndef	_CellBarred_H_
#define	_CellBarred_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CellBarred {
	CellBarred_barred	= 0,
	CellBarred_not_barred	= 1
	/*
	 * Enumeration is extensible
	 */
} e_CellBarred;

/* CellBarred */
typedef long	 CellBarred_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CellBarred_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CellBarred;
extern const asn_INTEGER_specifics_t asn_SPC_CellBarred_specs_1;
asn_struct_free_f CellBarred_free;
asn_struct_print_f CellBarred_print;
asn_constr_check_f CellBarred_constraint;
ber_type_decoder_f CellBarred_decode_ber;
der_type_encoder_f CellBarred_encode_der;
xer_type_decoder_f CellBarred_decode_xer;
xer_type_encoder_f CellBarred_encode_xer;
oer_type_decoder_f CellBarred_decode_oer;
oer_type_encoder_f CellBarred_encode_oer;
per_type_decoder_f CellBarred_decode_uper;
per_type_encoder_f CellBarred_encode_uper;
per_type_decoder_f CellBarred_decode_aper;
per_type_encoder_f CellBarred_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _CellBarred_H_ */
#include <asn_internal.h>
