/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1.asn1"
 * 	`asn1c -D ./out -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-example`
 */

#ifndef	_ProtectedEUTRAResourceIndication_H_
#define	_ProtectedEUTRAResourceIndication_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProtectedEUTRAResourceIndication */
typedef OCTET_STRING_t	 ProtectedEUTRAResourceIndication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtectedEUTRAResourceIndication;
asn_struct_free_f ProtectedEUTRAResourceIndication_free;
asn_struct_print_f ProtectedEUTRAResourceIndication_print;
asn_constr_check_f ProtectedEUTRAResourceIndication_constraint;
ber_type_decoder_f ProtectedEUTRAResourceIndication_decode_ber;
der_type_encoder_f ProtectedEUTRAResourceIndication_encode_der;
xer_type_decoder_f ProtectedEUTRAResourceIndication_decode_xer;
xer_type_encoder_f ProtectedEUTRAResourceIndication_encode_xer;
oer_type_decoder_f ProtectedEUTRAResourceIndication_decode_oer;
oer_type_encoder_f ProtectedEUTRAResourceIndication_encode_oer;
per_type_decoder_f ProtectedEUTRAResourceIndication_decode_uper;
per_type_encoder_f ProtectedEUTRAResourceIndication_encode_uper;
per_type_decoder_f ProtectedEUTRAResourceIndication_decode_aper;
per_type_encoder_f ProtectedEUTRAResourceIndication_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtectedEUTRAResourceIndication_H_ */
#include <asn_internal.h>
