/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1.asn1"
 * 	`asn1c -D ./out -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-example`
 */

#ifndef	_ShortDRXCycleTimer_H_
#define	_ShortDRXCycleTimer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ShortDRXCycleTimer */
typedef long	 ShortDRXCycleTimer_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ShortDRXCycleTimer_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ShortDRXCycleTimer;
asn_struct_free_f ShortDRXCycleTimer_free;
asn_struct_print_f ShortDRXCycleTimer_print;
asn_constr_check_f ShortDRXCycleTimer_constraint;
ber_type_decoder_f ShortDRXCycleTimer_decode_ber;
der_type_encoder_f ShortDRXCycleTimer_encode_der;
xer_type_decoder_f ShortDRXCycleTimer_decode_xer;
xer_type_encoder_f ShortDRXCycleTimer_encode_xer;
oer_type_decoder_f ShortDRXCycleTimer_decode_oer;
oer_type_encoder_f ShortDRXCycleTimer_encode_oer;
per_type_decoder_f ShortDRXCycleTimer_decode_uper;
per_type_encoder_f ShortDRXCycleTimer_encode_uper;
per_type_decoder_f ShortDRXCycleTimer_decode_aper;
per_type_encoder_f ShortDRXCycleTimer_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ShortDRXCycleTimer_H_ */
#include <asn_internal.h>
