/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "F1.asn1"
 * 	`asn1c -D ./out -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-example`
 */

#include "UE-associatedLogicalF1-ConnectionItem.h"

#include "ProtocolExtensionContainer.h"
static asn_TYPE_member_t asn_MBR_UE_associatedLogicalF1_ConnectionItem_1[] = {
	{ ATF_POINTER, 3, offsetof(struct UE_associatedLogicalF1_ConnectionItem, gNB_CU_UE_F1AP_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GNB_CU_UE_F1AP_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gNB-CU-UE-F1AP-ID"
		},
	{ ATF_POINTER, 2, offsetof(struct UE_associatedLogicalF1_ConnectionItem, gNB_DU_UE_F1AP_ID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GNB_DU_UE_F1AP_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gNB-DU-UE-F1AP-ID"
		},
	{ ATF_POINTER, 1, offsetof(struct UE_associatedLogicalF1_ConnectionItem, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_4624P110,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_UE_associatedLogicalF1_ConnectionItem_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_UE_associatedLogicalF1_ConnectionItem_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UE_associatedLogicalF1_ConnectionItem_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* gNB-CU-UE-F1AP-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* gNB-DU-UE-F1AP-ID */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_UE_associatedLogicalF1_ConnectionItem_specs_1 = {
	sizeof(struct UE_associatedLogicalF1_ConnectionItem),
	offsetof(struct UE_associatedLogicalF1_ConnectionItem, _asn_ctx),
	asn_MAP_UE_associatedLogicalF1_ConnectionItem_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_UE_associatedLogicalF1_ConnectionItem_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UE_associatedLogicalF1_ConnectionItem = {
	"UE-associatedLogicalF1-ConnectionItem",
	"UE-associatedLogicalF1-ConnectionItem",
	&asn_OP_SEQUENCE,
	asn_DEF_UE_associatedLogicalF1_ConnectionItem_tags_1,
	sizeof(asn_DEF_UE_associatedLogicalF1_ConnectionItem_tags_1)
		/sizeof(asn_DEF_UE_associatedLogicalF1_ConnectionItem_tags_1[0]), /* 1 */
	asn_DEF_UE_associatedLogicalF1_ConnectionItem_tags_1,	/* Same as above */
	sizeof(asn_DEF_UE_associatedLogicalF1_ConnectionItem_tags_1)
		/sizeof(asn_DEF_UE_associatedLogicalF1_ConnectionItem_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_UE_associatedLogicalF1_ConnectionItem_1,
	3,	/* Elements count */
	&asn_SPC_UE_associatedLogicalF1_ConnectionItem_specs_1	/* Additional specs */
};

