---
name: Gerrit Merge

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    secrets:
      SONAR_TOKEN:
        description: "Sonar Cloud access token"
        required: true

concurrency:
  # yamllint disable-line rule:line-length
  group: gerrit-merge-${{ github.workflow }}-${{ github.event.inputs.GERRIT_CHANGE_ID || github.run_id }}
  cancel-in-progress: true

jobs:

  sonarqube-cloud:
    needs: notify
    # yamllint disable-line rule:line-length
    uses: lfit/releng-reusable-workflows/.github/workflows/reuse-sonarqube-cloud.yaml@0f26b956d7d4bef97a5ef0099a142eb7c9242d1c # 2025-02-10
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
