---
name: Gerrit Merge

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    secrets:
      SONAR_TOKEN:
        description: "Sonar Cloud access token"
        required: true

concurrency:
  # yamllint disable-line rule:line-length
  group: gerrit-merge-${{ github.workflow }}-${{ github.event.inputs.GERRIT_CHANGE_ID || github.run_id }}
  cancel-in-progress: true

jobs:
  sonarqube-cloud:
    name: "SonarQube Cloud"
    # yamllint disable-line rule:line-length
    uses: ./.github/workflows/reuse-sonarqube-cloud.yaml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
